volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/glaguyon/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/glaguyon/data/wordpress
      o: bind
      type: none
networks:
  inception:
    name: inception
    driver: bridge
services:
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks: 
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
      - wordpress
    expose:
      - "443:443"
    restart: unless-stopped